# Generated by Django 3.2.12 on 2022-04-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
