# Generated by Django 3.2.12 on 2022-04-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderupdate_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='product_name',
        ),
    ]
