# Generated by Django 3.2.12 on 2022-04-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_orderupdate_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='timestap',
            new_name='timestamp',
        ),
    ]
